
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtdpbaepkpygbxpsjraj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZHBiYWVwa3B5Z2J4cHNqcmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjYzODAsImV4cCI6MjA2MzE0MjM4MH0.Bzat0I4TQubfAVRUc4wTbhuAhmX1sCWZ5cLskynD78g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
